language: python
python:
  - "3.9"
services:
  - docker
install:
  - pip install -r requirements.txt
script:
  - python -m unittest
  - bandit -r app.py
stages:
  - name: test-sast
    script: bandit -r app.py
deploy:
  provider: script
  script: 
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker tag myapp $DOCKER_USERNAME/myapp
    - docker push $DOCKER_USERNAME/myapp
    - export TELEGRAM_SH_PATH=$TRAVIS_BUILD_DIR/telegram.sh
    - chmod +x $TELEGRAM_SH_PATH
    - bash $TELEGRAM_SH_PATH "Deployment completed!"
  on:
    branch: main
  cleanup: false
