language: python
python:
  - "3.9"
services:
  - docker
install:
  - pip install -r requirements.txt

stages:
  - name: test-sast
    script:
      - python -m unittest
      - export TELEGRAM_SH_PATH=$TRAVIS_BUILD_DIR/telegram.sh
      - chmod +x $TELEGRAM_SH_PATH
      - if [ $TRAVIS_TEST_RESULT -eq 0 ]; then bash $TELEGRAM_SH_PATH "SAST scan succeeded!"; else bash $TELEGRAM_SH_PATH "SAST scan failed!"; fi

  - name: deploy
    if: type = push AND branch = main
    script:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker tag myapp $DOCKER_USERNAME/myapp
      - docker push $DOCKER_USERNAME/myapp
      - export TELEGRAM_SH_PATH=$TRAVIS_BUILD_DIR/telegram.sh
      - chmod +x $TELEGRAM_SH_PATH
      - bash $TELEGRAM_SH_PATH "Deployment completed!"
    cleanup: false

  - name: notify-pull-request
    if: type = pull_request
    script:
      - export TELEGRAM_SH_PATH=$TRAVIS_BUILD_DIR/telegram.sh
      - chmod +x $TELEGRAM_SH_PATH
      - bash $TELEGRAM_SH_PATH "Pull request created or updated!"
