language: python
python:
  - "3.9"
services:
  - docker
install:
  - pip install -r requirements.txt
script:
  - python -m unittest
  - bandit -r app.py
  - docker build -t myapp .
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: main
