language: python
python:
  - "3.9"
services:
  - docker
stages:
  - build
  - test
  - deploy
install:
  - pip install -r requirements.txt
build:
  stage: build
  script:
    - docker build --target test -t myapp-test .
    - docker run myapp-test python -m unittest
    - bandit -r app.py
sast:
  stage: test
  script:
    - bandit -r app.py || true
deploy:
  stage: deploy
  provider: script
  script: 
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker tag myapp $DOCKER_USERNAME/myapp
    - docker push $DOCKER_USERNAME/myapp
    - telegram-send "Deployment completed!"
  on:
    branch: main
  skip_cleanup: true
